version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: KEA-CC-2024
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Change this!
      MYSQL_DATABASE: KEA-CC-2024
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminadmin # Change this!
    ports:
      - "3318:3306" # use port 3318 for mysql connect
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
